Repository getodk/briefcase, pull requests merged in 2018-03, with the labels that each got.

#393 Fix #378 - Allow yyyy/MM/dd and yyyy-MM-dd for start and end dates.
  src/org/opendatakit/briefcase/operations/Export.java
  src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
  src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
  src/org/opendatakit/common/cli/Param.java
  test/java/org/opendatakit/common/cli/ParamTest.java
Labels: behavior verified

#404 Add option to overwrite existing files
  src/org/opendatakit/briefcase/export/ExportAction.java
  src/org/opendatakit/briefcase/export/ExportConfiguration.java
  src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java
  src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form
  src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
Labels: behavior verified

#410 Spelling error
  test/java/org/opendatakit/briefcase/export/ExportConfigurationTest.java
Labels: reviewed

#407 Add whitespace to help text
  src/org/opendatakit/common/cli/Param.java
Labels: reviewed

#411 UX clean up for overwrite existing files feature
  src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.form
  src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java
Labels: behavior verified, reviewed

#417 show exporting feedback label. closes #402
  src/org/opendatakit/briefcase/ui/export/ExportPanel.java
  src/org/opendatakit/briefcase/ui/export/ExportPanelForm.form
  src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java
Labels: reviewed

#415 Made startup message for ODK friendlier and easier to understand.
  src/org/opendatakit/briefcase/ui/MessageStrings.java
Labels: reviewed
