Repository getodk/briefcase, pull requests merged in 2018-02, with the labels that each got.

#361 New CLI op to clean prefs
  src/org/opendatakit/briefcase/Launcher.java
  src/org/opendatakit/briefcase/model/BriefcasePreferences.java
  src/org/opendatakit/briefcase/operations/ClearPreferences.java
Labels: reviewed

#359 Fixes all compilation warnings
  src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java
  src/org/opendatakit/briefcase/ui/FormTransferTable.java
  src/org/opendatakit/briefcase/util/FormCache.java
Labels: reviewed

#364 Remove aggregate 1.0 text
  src/org/opendatakit/briefcase/model/EndPointType.java
  src/org/opendatakit/briefcase/ui/ServerConnectionDialog.java
  src/org/opendatakit/briefcase/util/AggregateUtils.java
Labels: reviewed

#365 Issue 334 Reset HTTP context whenever we get an 401 Not Authorized response
  src/org/opendatakit/briefcase/ui/PullTransferPanel.java
  src/org/opendatakit/briefcase/util/AggregateUtils.java
  src/org/opendatakit/briefcase/util/WebUtils.java
Labels: reviewed

#367 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: reviewed

#377 Update README.md file
  README.md
Labels: reviewed

#376 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: reviewed

#354 Briefcase analytics
  .gitignore
  build.gradle
  src/org/opendatakit/briefcase/model/BriefcaseAnalytics.java
  src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
  src/org/opendatakit/briefcase/ui/PullTransferPanel.java
  src/org/opendatakit/briefcase/ui/PushTransferPanel.java
  src/org/opendatakit/briefcase/ui/SettingsPanel.java
  src/org/opendatakit/briefcase/ui/export/ExportPanel.java
  src/org/opendatakit/briefcase/ui/reused/Analytics.java
  test/java/org/opendatakit/briefcase/model/BriefcaseAnalyticsTest.java
  test/java/org/opendatakit/briefcase/ui/export/ExportPanelPageObject.java
  test/java/org/opendatakit/briefcase/ui/export/ExportPanelUnitTest.java
  test/java/org/opendatakit/briefcase/ui/reused/NoOpAnalytics.java
Labels: behavior verified, needs review

#381 Sentry integration
  .gitignore
  build.gradle
  res/logback.xml.example
  res/logback.xml.example-release
  res/simplelogger.properties.example
  res/simplelogger.properties.example_complete
  src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java
  src/org/opendatakit/briefcase/Launcher.java
  src/org/opendatakit/briefcase/export/ExportAction.java
  src/org/opendatakit/briefcase/model/BriefcaseFormDefinition.java
  src/org/opendatakit/briefcase/model/TerminationFuture.java
  src/org/opendatakit/briefcase/operations/CliEventsCompanion.java
  src/org/opendatakit/briefcase/operations/Common.java
  src/org/opendatakit/briefcase/operations/Export.java
  src/org/opendatakit/briefcase/operations/ImportFromODK.java
  src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java
  src/org/opendatakit/briefcase/transfer/NewTransferAction.java
  src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
  src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java
  src/org/opendatakit/briefcase/ui/FormTransferTable.java
  src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
  src/org/opendatakit/briefcase/ui/MainClearBriefcasePreferencesWindow.java
  src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java
  src/org/opendatakit/briefcase/ui/ScrollingStatusListDialog.java
  src/org/opendatakit/briefcase/ui/StorageLocation.java
  src/org/opendatakit/briefcase/util/AggregateUtils.java
  src/org/opendatakit/briefcase/util/BadXMLFixer.java
  src/org/opendatakit/briefcase/util/CipherFactory.java
  src/org/opendatakit/briefcase/util/DatabaseUtils.java
  src/org/opendatakit/briefcase/util/EncryptionInformation.java
  src/org/opendatakit/briefcase/util/ExportToCsv.java
  src/org/opendatakit/briefcase/util/FileSystemUtils.java
  src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
  src/org/opendatakit/briefcase/util/ServerFetcher.java
  src/org/opendatakit/briefcase/util/ServerUploader.java
  src/org/opendatakit/briefcase/util/TransferAction.java
  src/org/opendatakit/briefcase/util/TransferFromODK.java
  src/org/opendatakit/briefcase/util/WebUtils.java
  src/org/opendatakit/briefcase/util/XmlManipulationUtils.java
  src/org/opendatakit/common/cli/Cli.java
  src/org/opendatakit/common/utils/WebUtils.java
  test/resources/logback-test.xml
Labels: reviewed

#375 Fix #352 - Bulk exporting more than one encrypted form fails.
  src/org/opendatakit/briefcase/util/ExportToCsv.java
Labels: behavior verified, reviewed

#382 Issue 196 describe log contribution guide
  .gitignore
  README.md
  res/logback.xml.example
  res/logback.xml.example-release
  test/resources/logback-test.xml.example
Labels: reviewed

#388 Provide a human-friendly error message
  src/org/opendatakit/common/cli/Cli.java
Labels: reviewed

#389 Replace anonymous types with their lambda equivalent
  src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java
  src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
  src/org/opendatakit/briefcase/ui/MainClearBriefcasePreferencesWindow.java
  src/org/opendatakit/briefcase/ui/MainFormUploaderWindow.java
  src/org/opendatakit/briefcase/ui/MountedSDCardChooserDialog.java
  src/org/opendatakit/briefcase/ui/PullTransferPanel.java
  src/org/opendatakit/briefcase/ui/PushTransferPanel.java
  src/org/opendatakit/briefcase/ui/SettingsPanel.java
  src/org/opendatakit/briefcase/ui/WrappedFileChooser.java
  src/org/opendatakit/briefcase/util/ExportToCsv.java
  src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
  src/org/opendatakit/briefcase/util/TransferFromODK.java
Labels: reviewed

#387 Update README.md
  README.md
Labels: reviewed

#391 Issue 384 Sentry metadata
  build.gradle
  src/org/opendatakit/briefcase/Launcher.java
  src/org/opendatakit/briefcase/util/FindDirectoryStructure.java
Labels: reviewed
