Repository getodk/briefcase, pull requests merged in 2019-08, with the labels that each got.

#769 Provide fallback cursor implementation
  src/org/opendatakit/briefcase/pull/aggregate/Cursor.java
  src/org/opendatakit/briefcase/pull/aggregate/OpaqueCursor.java
  test/java/org/opendatakit/briefcase/pull/aggregate/AggregateCursorTest.java
  test/java/org/opendatakit/briefcase/pull/aggregate/CursorHelpers.java
  test/java/org/opendatakit/briefcase/pull/aggregate/CursorTest.java
Labels: bug, high priority

#778 Issue 777 Latest Central rejects multiple simultaneous auth methods
  src/org/opendatakit/briefcase/reused/http/CommonsHttp.java
Labels: behavior verified, bug, ready

#790 Issue #789 Catch NPE while populating dynamic choices
  src/org/opendatakit/briefcase/export/FormDefinition.java
  test/java/org/opendatakit/briefcase/export/ExportToCsvExplodeChoiceListWithRelativePredicateInRepeatTest.java
  test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat-group.csv.expected
  test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat-submission.xml
  test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat.csv.expected
  test/resources/org/opendatakit/briefcase/export/choice-lists-predicate-relative-repeat.xml
Labels: behavior verified, bug, high priority

#792 Issue #791 Match case when finding xml element
  src/org/opendatakit/briefcase/export/XmlElement.java
  test/java/org/opendatakit/briefcase/export/ExportToCsvCaseSensitivityTest.java
  test/resources/org/opendatakit/briefcase/export/simple-form-case-sensitivity-submission.xml
  test/resources/org/opendatakit/briefcase/export/simple-form-case-sensitivity.csv.expected
  test/resources/org/opendatakit/briefcase/export/simple-form-case-sensitivity.xml
Labels: behavior verified, bug, high priority

#758 Issue 744 validate aggregate & central dialogs
  src/org/opendatakit/briefcase/reused/transfer/AggregateServer.java
  src/org/opendatakit/briefcase/reused/transfer/CentralServer.java
  src/org/opendatakit/briefcase/ui/reused/FocusAdapterBuilder.java
  src/org/opendatakit/briefcase/ui/reused/KeyAdapterBuilder.java
  src/org/opendatakit/briefcase/ui/reused/UI.java
  src/org/opendatakit/briefcase/ui/reused/UiFieldValidator.java
  src/org/opendatakit/briefcase/ui/reused/UiLinkedFieldValidator.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/AggregateServerDialog.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/AggregateServerDialogForm.form
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/AggregateServerDialogForm.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/CentralServerDialog.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/CentralServerDialogForm.form
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/CentralServerDialogForm.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Aggregate.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/PullSource.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/PushTarget.java
  test/java/org/opendatakit/briefcase/reused/transfer/AggregateServerTest.java
  test/java/org/opendatakit/briefcase/reused/transfer/CentralServerTest.java
  test/java/org/opendatakit/briefcase/ui/reused/UITest.java
  test/java/org/opendatakit/briefcase/ui/reused/UiFieldValidatorTest.java
  test/java/org/opendatakit/briefcase/ui/reused/UiLinkedFieldValidatorTest.java
  test/java/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/AggregateServerDialogTest.java
Labels: behavior verified, ready

#776 Fix #735 - Provide message when pulling non-existent form from odk dir using cmd
  src/org/opendatakit/briefcase/operations/ImportFromODK.java
Labels: behavior verified, ready

#782 Fix #755 - Set appropriate colour of view form details button.
  src/org/opendatakit/briefcase/ui/reused/UI.java
Labels: behavior verified, ready

#788 775: Push all forms to Aggregate if a form ID is not provided
  src/org/opendatakit/briefcase/operations/PushFormToAggregate.java
  src/org/opendatakit/briefcase/transfer/TransferForms.java
Labels: behavior verified, ready

#771 Issue 743 update notifications
  src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
  src/org/opendatakit/briefcase/ui/reused/SwingUtils.java
  src/org/opendatakit/briefcase/ui/reused/UI.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Aggregate.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Central.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/Aggregate.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/Central.java
  src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java
  src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.form
  src/org/opendatakit/briefcase/ui/settings/SettingsPanelForm.java
  src/org/opendatakit/briefcase/util/BriefcaseVersionManager.java
  test/java/org/opendatakit/briefcase/util/BriefcaseVersionManagerTest.java
Labels: behavior verified, ready

#766 Form metadata files and smart append
  config/checkstyle/checkstyle.xml
  src/org/opendatakit/briefcase/export/CsvLine.java
  src/org/opendatakit/briefcase/export/CsvLines.java
  src/org/opendatakit/briefcase/export/CsvSubmissionMappers.java
  src/org/opendatakit/briefcase/export/ExportConfiguration.java
  src/org/opendatakit/briefcase/export/ExportEvent.java
  src/org/opendatakit/briefcase/export/ExportToCsv.java
  src/org/opendatakit/briefcase/export/ExportToGeoJson.java
  src/org/opendatakit/briefcase/export/SubmissionParser.java
  src/org/opendatakit/briefcase/export/XmlElement.java
  src/org/opendatakit/briefcase/model/BriefcasePreferences.java
  src/org/opendatakit/briefcase/model/FormStatus.java
  src/org/opendatakit/briefcase/model/form/AsJson.java
  src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java
  src/org/opendatakit/briefcase/model/form/FormKey.java
  src/org/opendatakit/briefcase/model/form/FormMetadata.java
  src/org/opendatakit/briefcase/model/form/FormMetadataCommands.java
  src/org/opendatakit/briefcase/model/form/FormMetadataPort.java
  src/org/opendatakit/briefcase/model/form/FormMetadataQueries.java
  src/org/opendatakit/briefcase/model/form/SubmissionExportMetadata.java
  src/org/opendatakit/briefcase/operations/Export.java
  src/org/opendatakit/briefcase/operations/PullFormFromAggregate.java
  src/org/opendatakit/briefcase/operations/PullFormFromCentral.java
  src/org/opendatakit/briefcase/pull/aggregate/AggregateCursor.java
  src/org/opendatakit/briefcase/pull/aggregate/Cursor.java
  src/org/opendatakit/briefcase/pull/aggregate/EmptyCursor.java
  src/org/opendatakit/briefcase/pull/aggregate/OnaCursor.java
  src/org/opendatakit/briefcase/pull/aggregate/OpaqueCursor.java
  src/org/opendatakit/briefcase/pull/aggregate/PullFromAggregate.java
  src/org/opendatakit/briefcase/pull/central/PullFromCentral.java
  src/org/opendatakit/briefcase/reused/LegacyPrefs.java
  src/org/opendatakit/briefcase/reused/job/Job.java
  src/org/opendatakit/briefcase/ui/BriefcaseCLI.java
  src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java
  src/org/opendatakit/briefcase/ui/export/ExportPanel.java
  src/org/opendatakit/briefcase/ui/pull/PullPanel.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Aggregate.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/Central.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/CustomDir.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/FormInComputer.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/PullSource.java
  src/org/opendatakit/briefcase/ui/settings/SettingsPanel.java
  test/java/org/opendatakit/briefcase/export/CsvLinesTest.java
  test/java/org/opendatakit/briefcase/export/ExportToCsvScenario.java
  test/java/org/opendatakit/briefcase/model/form/AsJsonTest.java
  test/java/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapterTest.java
  test/java/org/opendatakit/briefcase/model/form/FormMetadataCommandsTest.java
  test/java/org/opendatakit/briefcase/model/form/FormMetadataQueriesTest.java
  test/java/org/opendatakit/briefcase/model/form/FormMetadataTest.java
  test/java/org/opendatakit/briefcase/model/form/InMemoryFormMetadataAdapter.java
  test/java/org/opendatakit/briefcase/model/form/SubmissionExportMetadataTest.java
  test/java/org/opendatakit/briefcase/pull/aggregate/AggregateCursorTest.java
  test/java/org/opendatakit/briefcase/pull/aggregate/PullFromAggregateIntegrationTest.java
  test/java/org/opendatakit/briefcase/pull/aggregate/PullFromAggregateTest.java
  test/java/org/opendatakit/briefcase/pull/central/PullFromCentralIntegrationTest.java
  test/java/org/opendatakit/briefcase/pull/central/PullFromCentralTest.java
  test/java/org/opendatakit/briefcase/ui/export/ExportPanelPageObject.java
  test/java/org/opendatakit/briefcase/ui/export/ExportPanelUnitTest.java
Labels: behavior verified, ready

#794 Fix #732 - Disable the select all button on Export tab if list is empty
  src/org/opendatakit/briefcase/export/ExportForms.java
  src/org/opendatakit/briefcase/ui/export/ExportPanel.java
  src/org/opendatakit/briefcase/ui/export/ExportPanelForm.java
Labels: behavior verified

#787 Fix #786 - Show error message when invalid project id is used for Central
  src/org/opendatakit/briefcase/reused/transfer/CentralServer.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/CentralServerDialog.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/source/PullSource.java
  src/org/opendatakit/briefcase/ui/reused/transfer/sourcetarget/target/PushTarget.java
Labels: behavior verified
